[build-system]
requires = [
    "setuptools>=67.6.0",
    "wheel>=0.40.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "cookiecutters"
version = "1.0.0"
dynamic = ["readme"]
requires-python = ">=3.10"
description = "Several useful cookiecutters"
keywords = [
]
authors = [
  { name="Benjamin P. Trachtenberg", email="e_ben_75-python@yahoo.com" },
]
maintainers = [
  {name = "Benjamin P. Trachtenberg", email = "e_ben_75-python@yahoo.com"},
]
license = "MIT"
license-files = [
    "LICENSE"
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX",
    "Operating System :: POSIX :: BSD",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]



dependencies = [
    "cookiecutter~=2.7.1",
    "urllib3>=2.7.0",
]

[dependency-groups]
dev = [
    "pytest-cov~=7.1.0",
    "pytest-cookies~=0.7.0",
    "pylint~=4.0.5",
    "pip-audit~=2.10.0",
    "black~=26.3.1",
    "bandit~=1.9.4",
]

[tool.setuptools.dynamic]
readme = {file = "README.md", content-type = "text/markdown"}

[tool.setuptools.packages.find]
include = [
    "ansible_collection",
    "go",
    "python_fastapi_openapi",
]


[tool.pytest.ini_options]
addopts = "--strict-markers"
markers = [
    "generic_tests: marks tests as generic_tests (deselect with -m not generic_tests)",
]
testpaths = [
    "ansible_collection/tests",
    "go/tests",
    "python_fastapi_openapi/tests",
    "python_library/tests",
]

[tool.coverage.run]
command_line= "-m pytest -vvv"

[tool.coverage.report]
include = [
    "ansible_collection/hooks/*",
    "go/hooks/*",
    "python_fastapi_openapi/hooks/*",
    "python_library/hooks/*",
]
fail_under = 70

[tool.pylint]
max-line-length = 120
# This allows pylint to complain on FIXME and XXX notes
notes = [
    "FIXME",
    "XXX",
]
fail-under = 9.9

[tool.black]
line-length = 120
target-version = [
    "py312",
]

[tool.bandit]
exclude_dirs = [
    "tests",
    "venv",
    ".venv",
    "docs",
    "{{cookiecutter.__git_repo_name}}",
    "{{cookiecutter.git_repo_name}}"
]

[tool.uv]
keyring-provider = "subprocess"
system-certs = true
